### PR TITLE
Add the Fbt library

### PR DESCRIPTION
**Pull request by retyui**
# Why

# Checklist

If you added a new library:

- [x] Added it to **react-native-libraries.json**

If you added a feature or fixed a bug:

- [ ] Documented in this PR how to use the feature or replicate the bug.
- [ ] Documented in this PR how you fixed or created the feature.

### CODE REVIEW

**Review by Simek — CHANGES_REQUESTED** [review]
I'm going to ask someone from FB, if they green light this addition. 

Also please add the libraries at the end of file, otherwise you are breaking the "Recently Added" order.

**Comment by retyui** [comment]
cc @jrwats @kayhadrin

**Comment by kayhadrin** [comment]
@Simek Yes, that should be fine. 
Thanks @retyui! :-)
cc: @dalmendray

**Review by Simek — APPROVED** [review]
Thank you! 👍

**Pull request merged**
