### PR TITLE
update to Next 11 and Webpack 5

### PR DESCRIPTION
**Pull request by Simek**
# Why

Refs https://github.com/expo/expo/pull/13684 & https://github.com/expo/examples/pull/280

This is an attempt to update RN Directory to use Next 11 and Webpack 5.

I have decided to push this changeset as a draft, because I have encountered an issue testing this locally.

I would like to see if the problem exist on the CI and I'd want to be able to share the code with others.

### CODE REVIEW

**Comment by Simek** [comment]
After latest changes and bump it looks like `build` and `dev` fails after a while with an error:

```
./node_modules/react-native-web/src/modules/UnimplementedView/index.js:24:17
Syntax error: Unexpected token, expected ","

  22 | 
  23 |   render(): Node {
> 24 |     return <View style={[unimplementedViewStyles, this.props.style]}>{this.props.children}</View>;
     |                  ^
  25 |   }
  26 | }
  27 | 
```

@axeldelafosse Maybe you will have any idea how to debug/fix this issue? 🙂

**Comment by axeldelafosse** [comment]
Hey @Simek! Sorry for the delay, I was working on something else. I have a fix for this but I don’t have write access to this repo so I can’t commit to your PR. Can you grant me write access to the repo please?

Or can you try with this Babel config please?

```
module.exports = {
  presets: [
    'next/babel',
    [
      'babel-preset-expo',
      {
        web: { useTransformReactJsxExperimental: true },
      },
    ],
  ],
  plugins: [
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    ['@babel/plugin-proposal-private-methods', { loose: true }],
    ['@babel/plugin-proposal-private-property-in-object', { loose: true }],
  ],
};
```

**Comment by Simek** [comment]
> Hey @Simek! Sorry for the delay, I was working on something else. I have a fix for this but I don’t have write access to this repo so I can’t commit to your PR. Can you grant me write access to the repo please?

No problem, invite sent! Unfortunately, with the current setup, to deploy a preview we need to have the PR branch directly in the main repository, otherwise I would use my fork. 🙂

**Comment by Simek** [comment]
Deploy preview is here: https://react-native-directory-efyn6l1jw-rndir.vercel.app/

The build log did not include any errors or warnings, everything looks fine, thank you @alexbrazier! 🙏

**Pull request merged**
