### PR TITLE
add stora to react-native-libraries.json

### PR DESCRIPTION
**Pull request by chengsokdara**
# Why

This PR add `stora` in react-native-libraries.json file.

# Checklist

If you added a new library:

- [x] Added it to **react-native-libraries.json**

### CODE REVIEW

**Review by Simek — CHANGES_REQUESTED** [review]
Hi @chengsokdara, unfortunately it looks like the library you want to add doesn't work with Expo:
* https://snack.expo.io/@simek/amused-churros

I'm also not able to find a `web` platform example anywhere, for some time we do not accept out-of-tree platforms support without a confirmation that library supports them, even with library is not using the native components. This is due to compatibility issues reported by directory users.

If you want to proceed with addition you need to provide more examples or you can just remove platforms in question for now, and add additional support later in time.

**Comment by chengsokdara** [comment]
@Simek Thank you for your response, I have solved conflicts and remove both web and expo from supported platform.

**Review by Simek — CHANGES_REQUESTED** [review]
Please run `yarn libraries:format` script to drop the formatting changes (running Git Hooks on commit also should fix the problem), I don't have a permission to push the changes to your branch.

BTW. How you have ended with this reformatting in the changeset? I would like to fix this issue, if you are able to provide steps to reproduce.

**Comment by chengsokdara** [comment]
@Simek Sorry it was me forgetting to yarn install so when I commit it didn't run husky. I did run yarn libraries:format just in case.

**Review by Simek — APPROVED** [review]
Thank you for the review updates! 👍

**Pull request merged**
