### PR TITLE
navigation refactor, footer update, popularity scoring tweaks

### PR DESCRIPTION
**Pull request by Simek**
# Why

After playing a bit with the new additions to the Directory @brentvatne suggested that the `ExploreNav` can be used as a global navigation.

This PR include the navigation refactor, new tabs style, labels and various tweaks related to the popularity scoring.

Also the Footer has been modified a bit, BLM banner has been moved there and Directory logo has been added as a bottom spacer.

# Checklist

- [X] Documented in this PR how you fixed or created the feature.

### CODE REVIEW

**Comment by Simek** [comment]
Hmm, it looks like that for some reason workflow cannot be completed, but the preview deploy was successful:
* https://react-native-directory-i4ywpdhq8-rndir.vercel.app/

I will investigate that further.

**Review by jonsamp — APPROVED** [review]
These changes look good to me. Can we add at least 80px of margin to the logo in the footer? We can use tons of space around that logo.
Screen Shot 2021-03-15 at 6 05 09 PM

I think this is good to go from a design-view though. Code looks reasonable as well.

**Comment by Simek** [comment]
@jonsamp Thank you for the review, that's a great idea, I will update to footer later today! 🙂

**Comment by Simek** [comment]
Update deploy: https://react-native-directory-3wvknbpw4-rndir.vercel.app/

**Review by brentvatne — APPROVED** [review]

**Comment by Simek** [comment]
Thank you for the review guys, it's deploy time than! 🚀

**Pull request merged**
