### PR TITLE
basic New Arch detection and new status

### PR DESCRIPTION
**Pull request by Simek**
# 📝 Why & how

Refs #830

This PR add a basic New Architecture support detection based on the present of the Codegen related field in the library `package.json`.

The status in display in the secondary metadata row and links to the New Architecture intro docs on the React Native docs website, which might help the directory users to understand what this term mean, if they sees it in library box.

---

Things to consider before converting from draft:
* should we allow users to manually add this flag to the JSON entries?
* should we add filter for this status (not sure if it is a good idea, until we are sure that this basic method won't cover almost all of the cases)

# 📸 Preview

https://react-native-directory-okpe29xli-rndir.vercel.app/

### Library Box

Screenshot 2022-08-21 191622

# ✅ Checklist

- [ ] Added library to **`react-native-libraries.json`**
- [ ] Updated library in **`react-native-libraries.json`**

- [ ] Documented in this PR how to use the feature or replicate the bug.
- [x] Documented in this PR how you fixed or created the feature.

### CODE REVIEW

**Comment by brentvatne** [comment]
> should we allow users to manually add this flag to the JSON entries?

yeah, we should! we take a different approach to supporting fabric in expo modules and the approach in this pr won't detect it

**Comment by brentvatne** [comment]
> should we add filter for this status (not sure if it is a good idea, until we are sure that this basic method won't cover almost all of the cases)

this could be useful. if we identify that something is wrong, we can adjust as we go

**Review by jonsamp — APPROVED** [review]
Thanks for adding this meta data!

**Review by cipolleschi — APPROVED** [review]

**Comment by cipolleschi** [comment]
> should we allow users to manually add this flag to the JSON entries?

What do you mean here? Lib maintainer has to manually add this entry in the `package.json`, otherwise the app can't generate the code it needs.

> should we add filter for this status

Which statuses are you considering? Something like: `In development`, `iOS done, Android not done`, or other.
I guess that for the sake of the user and of simplicity, we should only use a simple boolean: whether the latest release support the new architecture or not.

**Comment by tomekzaw** [comment]
> should we allow users to manually add this flag to the JSON entries?

React Native Reanimated also supports the New Architecture but doesn't have any native components or TurboModules, so the possibility to override this flag in `react-native-libraries.json` would be very appreciated.

**Review by brentvatne — APPROVED** [review]

**Pull request merged**
