### PR TITLE
Add dripsy

### PR DESCRIPTION
**Pull request by nandorojo**
[Dripsy](https://github.com/nandorojo/dripsy) is a responsive, theme-based design system for Expo + React Native for Web. I maintain it.

### CODE REVIEW

**Comment by Simek** [comment]
Hi @nandorojo, did you rest this library with `react-native-windows` and `react-native-macos`? I did not see any reference to those platform in the repository. Also the feature list states:
* Universal (Android, iOS, Web)

With no mention about the desktop RN platforms support.

**Comment by nandorojo** [comment]
Oh whoops, I marked every platform as true since it uses the standard Dimensions API on those, but I haven't done extensive testing, so I'm fine with removing windows and macOS.

**Review by Simek — APPROVED** [review]
Thank you for addition! 👍 

Feel free to add the desktop platforms later in time, when you test and verify that your library is working fine with them.

**Comment by nandorojo** [comment]
Sounds good, appreciate the quick merge!

**Pull request merged**
