### PR TITLE
Add `@korekoi/react-native-get-random-values`

### PR DESCRIPTION
**Pull request by andreazllin**
# 📝 Why & how

# ✅ Checklist

- [x] Added library to **`react-native-libraries.json`**
- [ ] Updated library in **`react-native-libraries.json`**

- [ ] Documented in this PR how to use the feature or replicate the bug.
- [ ] Documented in this PR how you fixed or created the feature.

### CODE REVIEW

**Comment by andreazllin** [comment]
@Simek It might be an error on my side, but I don't get why it isn't passing validation

**Comment by Simek** [comment]
Hey @andreazllin, there was a problem with CI validation, and it should be fixed now, sorry about that!

 After rebasing your PR, the newly triggered check should pass.

**Comment by andreazllin** [comment]
@Simek Thanks for letting me know, just pushed the rebase!

**Review by Simek — APPROVED** [review]
Thanks for the update! 👍

**Pull request merged**
