### PR TITLE
add react-native-ui-lib in json file

### PR DESCRIPTION
**Pull request by luism3861**
# Why
 This PR add [`react-native-ui-lib`](https://github.com/wix/react-native-ui-lib) in json file.

 # Checklist
 * [x]  Added it to **react-native-libraries.json**

### CODE REVIEW

**Comment by darkworks** [comment]
wow how come this wix is not in directory nd why this PR is not merged yet , lib seems very good

**Comment by luism3861** [comment]
hi @Simek can you take a look for this PR!.

**Comment by Simek** [comment]
Hi @luism3861, I don't remember why this was not accepted right away and was put on hold, but probably there was a reason. 

Since particular company it's behind this library it would be nice to ask owners first. Do you have any contact point in Wix?

**Comment by luism3861** [comment]
> Hi @luism3861, I don't remember why this was not accepted right away and was put on hold, but probably there was a reason.
> 
> Since company it's behind this library it would be nice to ask owners first. Do you have any contact point in @wix?

@Simek  unfortunately i don't any contact in wix

**Review by Simek — APPROVED** [review]
Let's add this library for now, sice we don't know the reason why it has been hold off before.

We can always revert it, if Wix reach which such request to us. 🙂

**Pull request merged**
