### PR TITLE
update re-state infos and add example

### PR DESCRIPTION
**Pull request by raulpesilva**
# 📝 Why & how

update re-state infos
- add windows and macos suport
- add example url

# ✅ Checklist

- [ ] Added library to **`react-native-libraries.json`**
- [x] Updated library in **`react-native-libraries.json`**

- [ ] Documented in this PR how to use the feature or replicate the bug.
- [ ] Documented in this PR how you fixed or created the feature.

### CODE REVIEW

**Review by Simek — COMMENTED** [review]
Hello @raulpesilva, thank you for the update! 👍 

Unfortunately, due to compatibility issues in the past, we require an example for the out-of-tree platforms support (macOS & Windows)? Can provide a link to the sample project or app which use re-state on those platforms?

**Comment by raulpesilva** [comment]
Hello @Simek, thanks to explain the requirement.

I'll provide this examples soon and reopen this PR. 😄

**Comment by raulpesilva** [comment]
hello @simek, if you can tell me if these examples are enough i would be very grateful.
https://github.com/raulpesilva/re-state/tree/master/examples

Thanks in advance.

**Comment by Simek** [comment]
Thant's nice, thank you for the updates! 👍 

I'm for the few days without my Windows machine, but example project looks fine at the first glance. I have only one question, in the `examples/react-native-win-mac/package.json` I cannot see the RN macOS dependency, have you tested this project on macOS?

**Comment by raulpesilva** [comment]
sorry I was hoping `react-native-windows` would handle this, but I've uploaded the two separately now

**Review by Simek — APPROVED** [review]
Thank you for the updates and all of the work you put into the examples! LGTM, let's ship it! 🎉

**Pull request merged**
