### PR TITLE
add VisionOS platform, initial data seed

### PR DESCRIPTION
**Pull request by Simek**
# 📝 Why & how

[React Native VisionOS](https://github.com/callstack/react-native-visionos) out-of-tree platform is getting some traction and userbase already, so it would be nice to include it in the directory.

The initial data seed has been based on the repos I have seen on X and verified by checking their repo code.

@okwasniewski Please let me know if I have missed some! Also happy to know if there is an indicator that library support VisionOS that we can check automatically when analyzing packages data.

# ✅ Checklist

- [ ] Added library to **`react-native-libraries.json`**
- [x] Updated library in **`react-native-libraries.json`**

- [x] Documented in this PR how to use the feature or replicate the bug.
- [ ] Documented in this PR how you fixed or created the feature.

# Preview

> [!important]
> Screen do not include all libraries marked as supported (only debug repos)!

screencapture-localhost-3000-2024-02-22-18_53_11

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

**Comment by Simek** [comment]
Preview: https://react-native-directory-49o8x1wfz-rndir.vercel.app/?visionos=true

**Review by okwasniewski — APPROVED** [review]
Looks great! Regarding discovery, libraries need to add `visionos` to Podspec so I would use that.

**Comment by thiagobrez** [comment]
@Simek `react-native-async-storage` also already released support: https://github.com/react-native-async-storage/async-storage/pull/1063

And [react-native-keychain](https://github.com/oblador/react-native-keychain/pull/622) should be close (approved, not yet released)

**Comment by Simek** [comment]
Thanks for the references @thiagobrez! Just added Async Storage support.

> And https://github.com/oblador/react-native-keychain/pull/622 should be close (approved, not yet released)

Let's follow up with a separate PR updating the status when it get releases.

**Pull request merged**
